// var: lama, bisa diubah, dan kurang aman
var nama = "Muhammad Yusuf Akram";
nama = "Muhammad Akram";
var nama ="Yusuf Akram"; // bisa deklarasi ulang
// let: bisa diubah, lebih aman tapi tidak bisa deklarasi ulang
let umur = 20;
umur = 18

let umur = 21; // error karena tidak bisa deklarasi ulang

// const: tidak bisa diubah dan Bisa dipakai untuk data tetap
const namaSekolah = "SMK_Alfalah";
namaSekolah = "SMA 12"; // error 
const namaSekolah = "SMA"; // error karena tidak bisa deklarasi ulang

// Contoh:
var hidup = "Hidup itu indah";
hidup = "mungking";

// Math Programming
const pi = 3.14;
let a = 10;
let b = 5;
console.log("Penjumlahan:", a + b);
console.log("Pengurangan:", a - b);
console.log("Perkalian:", a * b);
console.log("Pembagian:", a / b);
console.log("Sisa bagi:", a % b);

let Luas = 10 * 7; 
console.log("Luas: ", Luas);  
